# This file was generated by GoReleaser. DO NOT EDIT.
class Horcrux < Formula
  desc "A program for splitting your files into encrypted fragments"
  homepage "https://github.com/jesseduffield/horcrux/"
  version "0.1"

  if OS.mac?
    url "https://github.com/jesseduffield/horcrux/releases/download/v0.1/horcrux_0.1_Darwin_x86_64.tar.gz"
    sha256 "ad013a96f8c3bb23d46e5878ea975d1ab56b545d68eb6122a71b27db89a0ff99"
  elsif OS.linux?
    url "https://github.com/jesseduffield/horcrux/releases/download/v0.1/horcrux_0.1_Linux_x86_64.tar.gz"
    sha256 "c53e3daef89e512536450c7cdac5fc2926c970693a6414d7b360f2d1c5dc4ff5"
  end

  def install
    bin.install "horcrux"
  end
end
